# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/munch-miuicamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),munch-miuicamera)

endif
